---
apiVersion: v2
name: ubuntu-base
description: ubuntu-base is an Ubuntu 24.04 image with additional essential dependencies for troubleshooting
type: application
version: 0.1.0
appVersion: 0.8.0
keywords:
  - base
sources:
  - https://github.com/GrabAByte/helm-grababyte-base
kubeVersion: '>= 1.24.0-0'
maintainers:
  - name: grababyte
    email: twr.devops@gmail.com
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/GrabAByte/helm-grababyte-base/tree/main/charts/ubuntu-base
  artifacthub.io/images: |
    - name: ubuntu-base
      image: ubuntu-base:0.8.0
